/* Code is built and compiled on IDEOne and Saving it here on Github */
/* 
Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/* Solution */

import java.util.*;
import java.lang.*;
import java.io.*;

class Ideone
{
	public static void main (String[] args) throws java.lang.Exception
	{
		int i=1, j=2, k=0, sum = j;
		System.out.print(i + " " + j + " ");
		while((k=i+j) < 4000000)
		{
			i = j; j =k;
			System.out.print(k + " ");
			if(k%2 == 0) sum+=k;
		}
		System.out.println("\nSum= " + sum);
	}
}

